version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: codeseer-postgres
    environment:
      POSTGRES_DB: codeseer
      POSTGRES_USER: codeseer
      POSTGRES_PASSWORD: codeseer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeseer -d codeseer"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: codeseer-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    container_name: codeseer-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - .env

  indexer:
    build: ./indexer
    container_name: codeseer-indexer
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - .env

  db-init:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db:/schema
    environment:
      PGPASSWORD: codeseer
    entrypoint: >
      bash -c "
      echo 'Applying schema...' &&
      ls -l /schema &&
      psql -h postgres -U codeseer -d codeseer -f /schema/schema.sql
      "


volumes:
  postgres_data:
  es_data:
