version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: codeseer-postgres
    environment:
      POSTGRES_USER: codeseer
      POSTGRES_PASSWORD: codeseer
      POSTGRES_DB: codeseer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: codeseer-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  api:
    build: ./api
    container_name: codeseer-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch

  indexer:
    build: ./indexer
    container_name: codeseer-indexer
    depends_on:
      - postgres
      - elasticsearch


volumes:
  postgres_data:
  es_data:
